name: settings
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yaru: ^0.1.5
  yaru_icons: ^0.0.5
  gsettings: ^0.1.2+1
  provider: ^5.0.0
  linux_system_info: ^0.0.7
  dbus: ^0.6.3
  duration: ^3.0.6
  filesize: ^2.0.1
  nm: ^0.4.0
  udisks: ^0.3.0
  upower: # ^0.6.1 (https://github.com/canonical/upower.dart/pull/17)
    git:
      url: https://github.com/canonical/upower.dart
  safe_change_notifier: ^0.0.1
  path_provider: ^2.0.5
  filesystem_picker:
    git:
      url: https://github.com/Feichtmeier/filesystem_picker
      path: package
  mime: ^1.0.0
  bluez: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockingjay: ^0.1.1
  build_runner: ^2.1.2
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cursor/
