name: settings
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dbus: ^0.6.3
  duration: ^3.0.6
  filesize: ^2.0.1
  filesystem_picker:
    git:
      url: https://github.com/Feichtmeier/filesystem_picker
      path: package
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gsettings: ^0.2.3
  intl: ^0.17.0
  linux_system_info: ^0.0.7
  mime: ^1.0.0
  bluez: ^0.7.4
  flex_color_picker: ^2.1.2
  nm: ^0.4.0
  open_file: ^3.2.1
  path_provider: ^2.0.5
  pdf: ^3.6.0
  provider: ^5.0.0
  rive: ^0.7.28
  safe_change_notifier: ^0.0.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  udisks: ^0.3.0
  upower:
    git:
      url: https://github.com/canonical/upower.dart
  yaru: ^0.1.7
  yaru_icons: ^0.0.7
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets.dart
  flutter_svg: ^1.0.0
  flutter_spinbox: ^0.7.0

dev_dependencies:
  build_runner: ^2.1.2

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.1.1
  mockito: ^5.0.16

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cursor/
    - assets/pdf_assets/cof.png
    - assets/rive/ubuntu_cof.riv
    - assets/images/active-screen-edges.svg
    - assets/images/workspaces-primary-display.svg
