name: yaru_settings
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  yaru: ^0.5.5
  yaru_widgets: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  test: ^1.21.4

flutter:
  uses-material-design: true
